repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: \.(html|htm)$
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
        - id: black
          args: ["--line-length=120"]